version: '3.8'
services:
  node:
    image: ghcr.io/gnosischain/gbc-lighthouse:v2.0.1-gbc
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --http-address 0.0.0.0
      --http
      --enr-address $PUBLIC_IP
      --enr-udp-port 12000
      --trusted-peers $TRUSTED_PEERS
      --debug-level $LOG_LEVEL
    ports:
      - '12000:12000/udp'
      - '13000:13000'
    volumes:
      - ./config:/root/sbc/config
      - /mnt/gbc-data/node_db:/home/.eth2/beaconchaindata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  node-private-slasher:
    image: ghcr.io/gnosischain/gbc-lighthouse:v2.0.1-gbc
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --slasher-dir /home/.eth2/slasherdata
      --http-address 0.0.0.0
      --http
      --trusted-peers $TRUSTED_PEERS
      --debug-level $LOG_LEVEL
      --slasher
      --slasher-max-db-size 32
    ports:
      - '12000:12000/udp'
      - '13000:13000'
    volumes:
      - ./config:/root/sbc/config
      - /mnt/gbc-data/node_db:/home/.eth2/beaconchaindata
      - /mnt/gbc-data/slasher_db:/home/.eth2/slasherdata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  node-public-slasher:
    image: ghcr.io/gnosischain/gbc-lighthouse:v2.0.1-gbc
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --slasher-dir /home/.eth2/slasherdata
      --http-address 0.0.0.0
      --http
      --trusted-peers $TRUSTED_PEERS
      --debug-level $LOG_LEVEL
      --slasher
      --slasher-max-db-size 32
      --slasher-broadcast
    volumes:
      - ./config:/root/sbc/config
      - /mnt/gbc-data/node_db:/home/.eth2/beaconchaindata
      - /mnt/gbc-data/slasher_db:/home/.eth2/slasherdata
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
  validator-import:
    image: ghcr.io/gnosischain/gbc-lighthouse:v2.0.1-gbc
    command: |
      lighthouse account_manager validator import
      --testnet-dir /root/sbc/config
      --password-file /root/sbc/keys/keystore_password.txt
      --reuse-password
      --directory /root/sbc/keys/validator_keys
      --datadir /root/sbc
    volumes:
      - ./config:/root/sbc/config
      - ./keys:/root/sbc/keys
      - ./validators:/root/sbc/validators
  validator:
    image: ghcr.io/gnosischain/gbc-lighthouse:v2.0.1-gbc
    depends_on:
      - node
    command: |
      lighthouse validator_client
      --testnet-dir /root/sbc/config
      --validators-dir /root/sbc/validators
      --beacon-nodes http://node:5052
    volumes:
      - ./config:/root/sbc/config
      - ./validators:/root/sbc/validators
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
